# Generated by Django 4.2.30 on 2026-04-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.CharField(max_length=255)),
                ('file_key', models.CharField(max_length=1000)),
                ('file_name', models.CharField(max_length=500)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('total_rows', models.IntegerField(default=0)),
                ('column_types', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Processing History',
                'verbose_name_plural': 'Processing Histories',
                'ordering': ['-processed_at'],
            },
        ),
    ]
